Menu.class: Menu.java
	javac -g Menu.java

Dealership.class: Dealership.java
	javac -g Dealership.java

TuningShop.class: TuningShop.java
	javac -g TuningShop.java

Garage.class: Garage.java
	javac -g Garage.java

Car.class: Car.java
	javac -g Car.java

CarBody.class: CarBody.java
	javac -g CarBody.java

Engine.class: Engine.java
	javac -g Engine.java

Transmission.class: Transmission.java
	javac -g Transmission.java

clean:
	rm *.class

run: Menu.class
	java Menu

